require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  IgnoredPatterns: ['\A#', '\A\s{2,}#']
